name = "rememo"
version = "3.3.0"

description = "Simple memoization for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "hunkyjimpjorps", repo = "rememo" }

internal_modules = [
  "internal/*"
]

[dependencies]
gleam_otp = "~> 0.10"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
javascript_mutable_reference = ">= 1.0.0 and < 2.0.0"
gtempo = ">= 7.2.2 and < 8.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_stdlib = ">= 0.67.1 and < 1.0.0"
dream_ets = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
